# SPDX-FileCopyrightText: 2026 Alper Çelik <alper@alper-celik.dev>
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0

volumes:
  pg_data:

services:
  db:
    image: postgres:18
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - 5555:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: "False"

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
